-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 22:15:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema habit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema habit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `habit` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `habit` ;

-- -----------------------------------------------------
-- Table `habit`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `habit`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `habit`.`habit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit`.`habit` (
  `habit_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `category_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`habit_id`),
  INDEX `fk_habit_category_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_habit_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_habit_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `habit`.`category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_habit_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `habit`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `habit`.`habitlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `habit`.`habitlog` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `log_date` DATE NOT NULL,
  `description` TEXT NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `duration` INT NOT NULL COMMENT 'Duration in minutes',
  `user_id` INT NOT NULL,
  `habit_id` INT NOT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_habitlog_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_habitlog_habit_idx` (`habit_id` ASC) VISIBLE,
  CONSTRAINT `fk_habitlog_habit`
    FOREIGN KEY (`habit_id`)
    REFERENCES `habit`.`habit` (`habit_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_habitlog_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `habit`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
